name: aiml
channels:
- anaconda
- conda-forge
- defaults
- districtdatalabs 
- plotly
dependencies:
- requests
- beautifulsoup4
- notebook 
- jupyter
- cython
- dask
- flask
- gevent
- greenlet
- matplotlib
- nbconvert
- nbformat
- nltk
- numba
- numexpr
- numpy
- openpyxl
- pandas
- pandoc
- patsy
- pillow
- pip
- pylint
- pyqt
- pytest
- scikit-image
- scikit-learn
- scipy
- seaborn
- statsmodels
- sympy
- tornado
- xlwt
- xlrd
- yellowbrick
- nltk 
- spacy
- plotly
- pyarrow
- opencv
- catboost 
- lightgbm
- tpot
- scikit-surprise
- pyldavis
- graphviz
- python-graphviz
- tensorflow
- pip:
  - pytest-cov
  - tables
  - stanfordcorenlp
  - sumy
  - sparkit-learn
  - sklearn-pandas
  - xgboost
  - gensim
