name: aiml
channels:
- anaconda
- conda-forge
- defaults
- districtdatalabs 
- plotly
- pytorch
dependencies:
- requests==2.24.0
- beautifulsoup4==4.9.1
- notebook==6.1.1
- jupyter==1.0.0
- cython==0.29.14
- dask==2.25.0
- flask==1.1.2
- gevent==20.6.2
- greenlet==0.4.16
- matplotlib==3.3.1
- nbconvert==5.6.1
- nbformat==5.0.7
- nltk==3.5
- numba==0.50.1
- numexpr==2.7.1
- numpy==1.19.1
- openpyxl==3.0.5
- pandas==1.1.1
- pandoc
- pip
- patsy==0.5.1
- pillow==7.2.0
- pylint==2.6.0
- pyqt
- pytest==6.0.1
- scikit-image==0.16.2
- scikit-learn==0.23.2
- scipy==1.5.2
- seaborn==0.11.0
- statsmodels==0.11.1
- sympy==1.6.2
- tornado==6.0.4
- xlwt==1.3.0
- xlrd==1.2.0
- yellowbrick==1.1
- nltk==3.5
- spacy==2.3.1
- plotly==4.9.0
- pyarrow==0.15.1
- opencv
- catboost==0.24
- lightgbm==2.3.0
- tpot==0.11.5
- scikit-surprise==1.1.1
- pyldavis==2.1.2
- graphviz
- python-graphviz==0.14.1
- tensorflow==2.1.0
- pytorch==1.6.0
- torchvision==0.7.0
- cpuonly
- ninja
- pip:
  - pytest-cov
  - tables==3.6.1
  - stanfordcorenlp==3.9.1.1
  - sumy==0.8.1
  - sparkit-learn==0.2.6
  - sklearn-pandas==2.0.1
  - xgboost==1.2.0
  - gensim==3.8.3
  


